# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gyuFiiR2Ms5ztA1NhJk7nezkgY_JmjMK
"""

name = input('Имя ')
print ('привет, ' + name)
